# Site settings
title: "Junteng Liu"
email: jliugi@connect.ust.hk
description: >-
  Junteng Liu's academic homepage. First-year PhD candidate at HKUST NLP Group.
  Research focuses on natural language processing and machine learning.
baseurl: "/LJT-Homepage"
url: "https://cerbarells1234-ci.github.io"

# Social networks
github_username: Vicent0205
scholar_userid: tbK9jl4AAAAJ
twitter_username: junteng88716710

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Collections
collections:
  publications:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
